/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as BranchDashboardRouteImport } from './routes/branch-dashboard'
import { Route as BranchManagerRouteImport } from './routes/branch-manager'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminCustomerReviewsRouteImport } from './routes/admin.customer-reviews'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminMenuAvailabilityRouteImport } from './routes/admin.menu-availability'
import { Route as AdminMenuInsightsRouteImport } from './routes/admin.menu-insights'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminSalesReportsRouteImport } from './routes/admin.sales-reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as BookBranchIdRouteImport } from './routes/book.$branchId'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as BranchManagerIndexRouteImport } from './routes/branch-manager.index'
import { Route as BranchManagerBookingsRouteImport } from './routes/branch-manager.bookings'
import { Route as BranchManagerCustomerReviewsRouteImport } from './routes/branch-manager.customer-reviews'
import { Route as BranchManagerInventoryRouteImport } from './routes/branch-manager.inventory'
import { Route as BranchManagerMenuAvailabilityRouteImport } from './routes/branch-manager.menu-availability'
import { Route as BranchManagerOrdersRouteImport } from './routes/branch-manager.orders'
import { Route as BranchManagerSalesReportsRouteImport } from './routes/branch-manager.sales-reports'
import { Route as BranchManagerSettingsRouteImport } from './routes/branch-manager.settings'
import { Route as DishIdRouteImport } from './routes/dish.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchDashboardRoute = BranchDashboardRouteImport.update({
  id: '/branch-dashboard',
  path: '/branch-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchManagerRoute = BranchManagerRouteImport.update({
  id: '/branch-manager',
  path: '/branch-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerReviewsRoute = AdminCustomerReviewsRouteImport.update({
  id: '/customer-reviews',
  path: '/customer-reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuAvailabilityRoute = AdminMenuAvailabilityRouteImport.update({
  id: '/menu-availability',
  path: '/menu-availability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuInsightsRoute = AdminMenuInsightsRouteImport.update({
  id: '/menu-insights',
  path: '/menu-insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesReportsRoute = AdminSalesReportsRouteImport.update({
  id: '/sales-reports',
  path: '/sales-reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const BookBranchIdRoute = BookBranchIdRouteImport.update({
  id: '/$branchId',
  path: '/$branchId',
  getParentRoute: () => BookRoute,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchManagerIndexRoute = BranchManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BranchManagerRoute,
} as any)
const BranchManagerBookingsRoute = BranchManagerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => BranchManagerRoute,
} as any)
const BranchManagerCustomerReviewsRoute =
  BranchManagerCustomerReviewsRouteImport.update({
    id: '/customer-reviews',
    path: '/customer-reviews',
    getParentRoute: () => BranchManagerRoute,
  } as any)
const BranchManagerInventoryRoute = BranchManagerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => BranchManagerRoute,
} as any)
const BranchManagerMenuAvailabilityRoute =
  BranchManagerMenuAvailabilityRouteImport.update({
    id: '/menu-availability',
    path: '/menu-availability',
    getParentRoute: () => BranchManagerRoute,
  } as any)
const BranchManagerOrdersRoute = BranchManagerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BranchManagerRoute,
} as any)
const BranchManagerSalesReportsRoute =
  BranchManagerSalesReportsRouteImport.update({
    id: '/sales-reports',
    path: '/sales-reports',
    getParentRoute: () => BranchManagerRoute,
  } as any)
const BranchManagerSettingsRoute = BranchManagerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BranchManagerRoute,
} as any)
const DishIdRoute = DishIdRouteImport.update({
  id: '/dish/$id',
  path: '/dish/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/branch-dashboard': typeof BranchDashboardRoute
  '/branch-manager': typeof BranchManagerRouteWithChildren
  '/branches': typeof BranchesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRouteWithChildren
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/customer-reviews': typeof AdminCustomerReviewsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/menu-availability': typeof AdminMenuAvailabilityRoute
  '/admin/menu-insights': typeof AdminMenuInsightsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/sales-reports': typeof AdminSalesReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$branchId': typeof BookBranchIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/branch-manager/bookings': typeof BranchManagerBookingsRoute
  '/branch-manager/customer-reviews': typeof BranchManagerCustomerReviewsRoute
  '/branch-manager/inventory': typeof BranchManagerInventoryRoute
  '/branch-manager/menu-availability': typeof BranchManagerMenuAvailabilityRoute
  '/branch-manager/orders': typeof BranchManagerOrdersRoute
  '/branch-manager/sales-reports': typeof BranchManagerSalesReportsRoute
  '/branch-manager/settings': typeof BranchManagerSettingsRoute
  '/dish/$id': typeof DishIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/branch-manager/': typeof BranchManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRouteWithChildren
  '/branch-dashboard': typeof BranchDashboardRoute
  '/branches': typeof BranchesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRouteWithChildren
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/customer-reviews': typeof AdminCustomerReviewsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/menu-availability': typeof AdminMenuAvailabilityRoute
  '/admin/menu-insights': typeof AdminMenuInsightsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/sales-reports': typeof AdminSalesReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$branchId': typeof BookBranchIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/branch-manager/bookings': typeof BranchManagerBookingsRoute
  '/branch-manager/customer-reviews': typeof BranchManagerCustomerReviewsRoute
  '/branch-manager/inventory': typeof BranchManagerInventoryRoute
  '/branch-manager/menu-availability': typeof BranchManagerMenuAvailabilityRoute
  '/branch-manager/orders': typeof BranchManagerOrdersRoute
  '/branch-manager/sales-reports': typeof BranchManagerSalesReportsRoute
  '/branch-manager/settings': typeof BranchManagerSettingsRoute
  '/dish/$id': typeof DishIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/admin': typeof AdminIndexRoute
  '/branch-manager': typeof BranchManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRouteWithChildren
  '/branch-dashboard': typeof BranchDashboardRoute
  '/branch-manager': typeof BranchManagerRouteWithChildren
  '/branches': typeof BranchesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRouteWithChildren
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/recommendations': typeof RecommendationsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/customer-reviews': typeof AdminCustomerReviewsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/menu-availability': typeof AdminMenuAvailabilityRoute
  '/admin/menu-insights': typeof AdminMenuInsightsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/sales-reports': typeof AdminSalesReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$branchId': typeof BookBranchIdRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/branch-manager/bookings': typeof BranchManagerBookingsRoute
  '/branch-manager/customer-reviews': typeof BranchManagerCustomerReviewsRoute
  '/branch-manager/inventory': typeof BranchManagerInventoryRoute
  '/branch-manager/menu-availability': typeof BranchManagerMenuAvailabilityRoute
  '/branch-manager/orders': typeof BranchManagerOrdersRoute
  '/branch-manager/sales-reports': typeof BranchManagerSalesReportsRoute
  '/branch-manager/settings': typeof BranchManagerSettingsRoute
  '/dish/$id': typeof DishIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/branch-manager/': typeof BranchManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/branch-dashboard'
    | '/branch-manager'
    | '/branches'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/menu'
    | '/orders'
    | '/portal'
    | '/profile'
    | '/promotions'
    | '/recommendations'
    | '/register'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/customer-reviews'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/menu-availability'
    | '/admin/menu-insights'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/sales-reports'
    | '/admin/settings'
    | '/book/$branchId'
    | '/bookings/$id'
    | '/branch-manager/bookings'
    | '/branch-manager/customer-reviews'
    | '/branch-manager/inventory'
    | '/branch-manager/menu-availability'
    | '/branch-manager/orders'
    | '/branch-manager/sales-reports'
    | '/branch-manager/settings'
    | '/dish/$id'
    | '/orders/$id'
    | '/admin/'
    | '/branch-manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/branch-dashboard'
    | '/branches'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/menu'
    | '/orders'
    | '/portal'
    | '/profile'
    | '/promotions'
    | '/recommendations'
    | '/register'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/customer-reviews'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/menu-availability'
    | '/admin/menu-insights'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/sales-reports'
    | '/admin/settings'
    | '/book/$branchId'
    | '/bookings/$id'
    | '/branch-manager/bookings'
    | '/branch-manager/customer-reviews'
    | '/branch-manager/inventory'
    | '/branch-manager/menu-availability'
    | '/branch-manager/orders'
    | '/branch-manager/sales-reports'
    | '/branch-manager/settings'
    | '/dish/$id'
    | '/orders/$id'
    | '/admin'
    | '/branch-manager'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/branch-dashboard'
    | '/branch-manager'
    | '/branches'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/menu'
    | '/orders'
    | '/portal'
    | '/profile'
    | '/promotions'
    | '/recommendations'
    | '/register'
    | '/sitemap.xml'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/customer-reviews'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/menu-availability'
    | '/admin/menu-insights'
    | '/admin/orders'
    | '/admin/overview'
    | '/admin/sales-reports'
    | '/admin/settings'
    | '/book/$branchId'
    | '/bookings/$id'
    | '/branch-manager/bookings'
    | '/branch-manager/customer-reviews'
    | '/branch-manager/inventory'
    | '/branch-manager/menu-availability'
    | '/branch-manager/orders'
    | '/branch-manager/sales-reports'
    | '/branch-manager/settings'
    | '/dish/$id'
    | '/orders/$id'
    | '/admin/'
    | '/branch-manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRouteWithChildren
  BranchDashboardRoute: typeof BranchDashboardRoute
  BranchManagerRoute: typeof BranchManagerRouteWithChildren
  BranchesRoute: typeof BranchesRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PortalRoute: typeof PortalRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BookingsIdRoute: typeof BookingsIdRoute
  DishIdRoute: typeof DishIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-dashboard': {
      id: '/branch-dashboard'
      path: '/branch-dashboard'
      fullPath: '/branch-dashboard'
      preLoaderRoute: typeof BranchDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-manager': {
      id: '/branch-manager'
      path: '/branch-manager'
      fullPath: '/branch-manager'
      preLoaderRoute: typeof BranchManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer-reviews': {
      id: '/admin/customer-reviews'
      path: '/customer-reviews'
      fullPath: '/admin/customer-reviews'
      preLoaderRoute: typeof AdminCustomerReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-availability': {
      id: '/admin/menu-availability'
      path: '/menu-availability'
      fullPath: '/admin/menu-availability'
      preLoaderRoute: typeof AdminMenuAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-insights': {
      id: '/admin/menu-insights'
      path: '/menu-insights'
      fullPath: '/admin/menu-insights'
      preLoaderRoute: typeof AdminMenuInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales-reports': {
      id: '/admin/sales-reports'
      path: '/sales-reports'
      fullPath: '/admin/sales-reports'
      preLoaderRoute: typeof AdminSalesReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/book/$branchId': {
      id: '/book/$branchId'
      path: '/$branchId'
      fullPath: '/book/$branchId'
      preLoaderRoute: typeof BookBranchIdRouteImport
      parentRoute: typeof BookRoute
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch-manager/': {
      id: '/branch-manager/'
      path: '/'
      fullPath: '/branch-manager/'
      preLoaderRoute: typeof BranchManagerIndexRouteImport
      parentRoute: typeof BranchManagerRoute
    }
    '/branch-manager/bookings': {
      id: '/branch-manager/bookings'
      path: '/bookings'
      fullPath: '/branch-manager/bookings'
      preLoaderRoute: typeof BranchManagerBookingsRouteImport
      parentRoute: typeof BranchManagerRoute
    }
    '/branch-manager/customer-reviews': {
      id: '/branch-manager/customer-reviews'
      path: '/customer-reviews'
      fullPath: '/branch-manager/customer-reviews'
      preLoaderRoute: typeof BranchManagerCustomerReviewsRouteImport
      parentRoute: typeof BranchManagerRoute
    }
    '/branch-manager/inventory': {
      id: '/branch-manager/inventory'
      path: '/inventory'
      fullPath: '/branch-manager/inventory'
      preLoaderRoute: typeof BranchManagerInventoryRouteImport
      parentRoute: typeof BranchManagerRoute
    }
    '/branch-manager/menu-availability': {
      id: '/branch-manager/menu-availability'
      path: '/menu-availability'
      fullPath: '/branch-manager/menu-availability'
      preLoaderRoute: typeof BranchManagerMenuAvailabilityRouteImport
      parentRoute: typeof BranchManagerRoute
    }
    '/branch-manager/orders': {
      id: '/branch-manager/orders'
      path: '/orders'
      fullPath: '/branch-manager/orders'
      preLoaderRoute: typeof BranchManagerOrdersRouteImport
      parentRoute: typeof BranchManagerRoute
    }
    '/branch-manager/sales-reports': {
      id: '/branch-manager/sales-reports'
      path: '/sales-reports'
      fullPath: '/branch-manager/sales-reports'
      preLoaderRoute: typeof BranchManagerSalesReportsRouteImport
      parentRoute: typeof BranchManagerRoute
    }
    '/branch-manager/settings': {
      id: '/branch-manager/settings'
      path: '/settings'
      fullPath: '/branch-manager/settings'
      preLoaderRoute: typeof BranchManagerSettingsRouteImport
      parentRoute: typeof BranchManagerRoute
    }
    '/dish/$id': {
      id: '/dish/$id'
      path: '/dish/$id'
      fullPath: '/dish/$id'
      preLoaderRoute: typeof DishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCustomerReviewsRoute: typeof AdminCustomerReviewsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminMenuAvailabilityRoute: typeof AdminMenuAvailabilityRoute
  AdminMenuInsightsRoute: typeof AdminMenuInsightsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSalesReportsRoute: typeof AdminSalesReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCustomerReviewsRoute: AdminCustomerReviewsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminMenuAvailabilityRoute: AdminMenuAvailabilityRoute,
  AdminMenuInsightsRoute: AdminMenuInsightsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSalesReportsRoute: AdminSalesReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BookRouteChildren {
  BookBranchIdRoute: typeof BookBranchIdRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookBranchIdRoute: BookBranchIdRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface BranchManagerRouteChildren {
  BranchManagerBookingsRoute: typeof BranchManagerBookingsRoute
  BranchManagerCustomerReviewsRoute: typeof BranchManagerCustomerReviewsRoute
  BranchManagerInventoryRoute: typeof BranchManagerInventoryRoute
  BranchManagerMenuAvailabilityRoute: typeof BranchManagerMenuAvailabilityRoute
  BranchManagerOrdersRoute: typeof BranchManagerOrdersRoute
  BranchManagerSalesReportsRoute: typeof BranchManagerSalesReportsRoute
  BranchManagerSettingsRoute: typeof BranchManagerSettingsRoute
  BranchManagerIndexRoute: typeof BranchManagerIndexRoute
}

const BranchManagerRouteChildren: BranchManagerRouteChildren = {
  BranchManagerBookingsRoute: BranchManagerBookingsRoute,
  BranchManagerCustomerReviewsRoute: BranchManagerCustomerReviewsRoute,
  BranchManagerInventoryRoute: BranchManagerInventoryRoute,
  BranchManagerMenuAvailabilityRoute: BranchManagerMenuAvailabilityRoute,
  BranchManagerOrdersRoute: BranchManagerOrdersRoute,
  BranchManagerSalesReportsRoute: BranchManagerSalesReportsRoute,
  BranchManagerSettingsRoute: BranchManagerSettingsRoute,
  BranchManagerIndexRoute: BranchManagerIndexRoute,
}

const BranchManagerRouteWithChildren = BranchManagerRoute._addFileChildren(
  BranchManagerRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRouteWithChildren,
  BranchDashboardRoute: BranchDashboardRoute,
  BranchManagerRoute: BranchManagerRouteWithChildren,
  BranchesRoute: BranchesRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PortalRoute: PortalRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  RecommendationsRoute: RecommendationsRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BookingsIdRoute: BookingsIdRoute,
  DishIdRoute: DishIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
